// Code generated by sqlc. DO NOT EDIT.
// source: businessLogs.sql

package pgdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBusinessLogs = `-- name: CreateBusinessLogs :exec
INSERT INTO 
  business_logs(event, device, os, ip, agent, position_id, company_id, role_id, team_id, app_id, creator)
VALUES 
  ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateBusinessLogsParams struct {
	Event      string        `db:"event" json:"event"`
	Device     string        `db:"device" json:"device"`
	Os         string        `db:"os" json:"os"`
	Ip         string        `db:"ip" json:"ip"`
	Agent      string        `db:"agent" json:"agent"`
	PositionID sql.NullInt64 `db:"position_id" json:"position_id"`
	CompanyID  sql.NullInt64 `db:"company_id" json:"company_id"`
	RoleID     int64         `db:"role_id" json:"role_id"`
	TeamID     sql.NullInt64 `db:"team_id" json:"team_id"`
	AppID      int64         `db:"app_id" json:"app_id"`
	Creator    uuid.UUID     `db:"creator" json:"creator"`
}

func (q *Queries) CreateBusinessLogs(ctx context.Context, arg CreateBusinessLogsParams) error {
	_, err := q.exec(ctx, q.createBusinessLogsStmt, createBusinessLogs,
		arg.Event,
		arg.Device,
		arg.Os,
		arg.Ip,
		arg.Agent,
		arg.PositionID,
		arg.CompanyID,
		arg.RoleID,
		arg.TeamID,
		arg.AppID,
		arg.Creator,
	)
	return err
}
