// Code generated by sqlc. DO NOT EDIT.
// source: user.create.sql

package pgdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCreds = `-- name: CreateCreds :one
INSERT INTO 
  creds(hashed_pass, rv)
VALUES 
  ($1, $2) RETURNING cred_id, created_at
`

type CreateCredsParams struct {
	HashedPass string `db:"hashed_pass" json:"hashed_pass"`
	Rv         int32  `db:"rv" json:"rv"`
}

type CreateCredsRow struct {
	CredID    uuid.UUID `db:"cred_id" json:"cred_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateCreds(ctx context.Context, arg CreateCredsParams) (CreateCredsRow, error) {
	row := q.queryRow(ctx, q.createCredsStmt, createCreds, arg.HashedPass, arg.Rv)
	var i CreateCredsRow
	err := row.Scan(&i.CredID, &i.CreatedAt)
	return i, err
}

const createUserBasic = `-- name: CreateUserBasic :one
INSERT INTO 
  users(email, username, status_id, cred_id, user_info_id, rv)
VALUES 
  ($1, $2, $3, $4, $5, $6) RETURNING user_id, email, username, user_info_id, created_at
`

type CreateUserBasicParams struct {
	Email      string    `db:"email" json:"email"`
	Username   string    `db:"username" json:"username"`
	StatusID   int64     `db:"status_id" json:"status_id"`
	CredID     uuid.UUID `db:"cred_id" json:"cred_id"`
	UserInfoID uuid.UUID `db:"user_info_id" json:"user_info_id"`
	Rv         int32     `db:"rv" json:"rv"`
}

type CreateUserBasicRow struct {
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	Email      string    `db:"email" json:"email"`
	Username   string    `db:"username" json:"username"`
	UserInfoID uuid.UUID `db:"user_info_id" json:"user_info_id"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateUserBasic(ctx context.Context, arg CreateUserBasicParams) (CreateUserBasicRow, error) {
	row := q.queryRow(ctx, q.createUserBasicStmt, createUserBasic,
		arg.Email,
		arg.Username,
		arg.StatusID,
		arg.CredID,
		arg.UserInfoID,
		arg.Rv,
	)
	var i CreateUserBasicRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Username,
		&i.UserInfoID,
		&i.CreatedAt,
	)
	return i, err
}

const createUserInfoBasic = `-- name: CreateUserInfoBasic :one
INSERT INTO 
  users_info(first_name, last_name, dob, rv)
VALUES 
  ($1, $2, $3, $4) RETURNING user_info_id, created_at
`

type CreateUserInfoBasicParams struct {
	FirstName sql.NullString `db:"first_name" json:"first_name"`
	LastName  sql.NullString `db:"last_name" json:"last_name"`
	Dob       time.Time      `db:"dob" json:"dob"`
	Rv        int32          `db:"rv" json:"rv"`
}

type CreateUserInfoBasicRow struct {
	UserInfoID uuid.UUID `db:"user_info_id" json:"user_info_id"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateUserInfoBasic(ctx context.Context, arg CreateUserInfoBasicParams) (CreateUserInfoBasicRow, error) {
	row := q.queryRow(ctx, q.createUserInfoBasicStmt, createUserInfoBasic,
		arg.FirstName,
		arg.LastName,
		arg.Dob,
		arg.Rv,
	)
	var i CreateUserInfoBasicRow
	err := row.Scan(&i.UserInfoID, &i.CreatedAt)
	return i, err
}

const createUserLog = `-- name: CreateUserLog :exec
INSERT INTO 
  user_logs(event, device, os, ip, agent, position_id, company_id, role_id, team_id, app_id, creator)
VALUES 
  ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateUserLogParams struct {
	Event      string    `db:"event" json:"event"`
	Device     string    `db:"device" json:"device"`
	Os         string    `db:"os" json:"os"`
	Ip         string    `db:"ip" json:"ip"`
	Agent      string    `db:"agent" json:"agent"`
	PositionID int64     `db:"position_id" json:"position_id"`
	CompanyID  int64     `db:"company_id" json:"company_id"`
	RoleID     int64     `db:"role_id" json:"role_id"`
	TeamID     int64     `db:"team_id" json:"team_id"`
	AppID      int64     `db:"app_id" json:"app_id"`
	Creator    uuid.UUID `db:"creator" json:"creator"`
}

func (q *Queries) CreateUserLog(ctx context.Context, arg CreateUserLogParams) error {
	_, err := q.exec(ctx, q.createUserLogStmt, createUserLog,
		arg.Event,
		arg.Device,
		arg.Os,
		arg.Ip,
		arg.Agent,
		arg.PositionID,
		arg.CompanyID,
		arg.RoleID,
		arg.TeamID,
		arg.AppID,
		arg.Creator,
	)
	return err
}

const createUserRoleAppCompany = `-- name: CreateUserRoleAppCompany :exec
INSERT INTO 
  users_roles_apps_companies(user_id, role_id, app_id, company_id, rv)
VALUES 
  ($1, $2, $3, $4, $5)
`

type CreateUserRoleAppCompanyParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	RoleID    int64     `db:"role_id" json:"role_id"`
	AppID     int64     `db:"app_id" json:"app_id"`
	CompanyID int64     `db:"company_id" json:"company_id"`
	Rv        int32     `db:"rv" json:"rv"`
}

func (q *Queries) CreateUserRoleAppCompany(ctx context.Context, arg CreateUserRoleAppCompanyParams) error {
	_, err := q.exec(ctx, q.createUserRoleAppCompanyStmt, createUserRoleAppCompany,
		arg.UserID,
		arg.RoleID,
		arg.AppID,
		arg.CompanyID,
		arg.Rv,
	)
	return err
}

const createUserRoleAppPositionTeamCompany = `-- name: CreateUserRoleAppPositionTeamCompany :exec
INSERT INTO 
  users_roles_apps_positions_teams_companies(user_id, role_id, app_id, position_id, team_id, company_id, rv)
VALUES 
  ($1, $2, $3, $4, $5, $6, $7)
`

type CreateUserRoleAppPositionTeamCompanyParams struct {
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	RoleID     int64     `db:"role_id" json:"role_id"`
	AppID      int64     `db:"app_id" json:"app_id"`
	PositionID int64     `db:"position_id" json:"position_id"`
	TeamID     int64     `db:"team_id" json:"team_id"`
	CompanyID  int64     `db:"company_id" json:"company_id"`
	Rv         int32     `db:"rv" json:"rv"`
}

func (q *Queries) CreateUserRoleAppPositionTeamCompany(ctx context.Context, arg CreateUserRoleAppPositionTeamCompanyParams) error {
	_, err := q.exec(ctx, q.createUserRoleAppPositionTeamCompanyStmt, createUserRoleAppPositionTeamCompany,
		arg.UserID,
		arg.RoleID,
		arg.AppID,
		arg.PositionID,
		arg.TeamID,
		arg.CompanyID,
		arg.Rv,
	)
	return err
}
