// Code generated by sqlc. DO NOT EDIT.

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAppBasic(ctx context.Context, arg CreateAppBasicParams) (CreateAppBasicRow, error)
	CreateBankAccountAllBasic(ctx context.Context, arg CreateBankAccountAllBasicParams) error
	CreateBankAccountBasic(ctx context.Context, arg CreateBankAccountBasicParams) (int64, error)
	CreateBusinessLogs(ctx context.Context, arg CreateBusinessLogsParams) (BusinessLog, error)
	CreateCompanyBasic(ctx context.Context, arg CreateCompanyBasicParams) (CreateCompanyBasicRow, error)
	CreateIndustryBasic(ctx context.Context, arg CreateIndustryBasicParams) (CreateIndustryBasicRow, error)
	CreatePositionBasic(ctx context.Context, arg CreatePositionBasicParams) (CreatePositionBasicRow, error)
	CreateRoleBasic(ctx context.Context, arg CreateRoleBasicParams) (CreateRoleBasicRow, error)
	CreateStatusBasic(ctx context.Context, arg CreateStatusBasicParams) (CreateStatusBasicRow, error)
	CreateTeamBasic(ctx context.Context, arg CreateTeamBasicParams) (CreateTeamBasicRow, error)
	CreateTeamsAppsCompanies(ctx context.Context, arg CreateTeamsAppsCompaniesParams) (CreateTeamsAppsCompaniesRow, error)
	DeleteApp(ctx context.Context, appID int64) error
	DeleteBankAccount(ctx context.Context, bankAccountID int64) error
	DeleteBankAccountAll(ctx context.Context, bankAccountAllID uuid.UUID) error
	DeleteCompany(ctx context.Context, companyID int32) error
	DeleteIndustry(ctx context.Context, industryID int64) error
	DeletePosition(ctx context.Context, positionID int64) error
	DeleteRole(ctx context.Context, roleID int64) error
	DeleteStatus(ctx context.Context, industryID int64) error
	DeleteTeam(ctx context.Context, teamID int64) error
	DeleteTeamsAppsCompanies(ctx context.Context, teamAppCompanyID int64) error
}

var _ Querier = (*Queries)(nil)
