// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID            int32        `db:"id" json:"id"`
	BankName      string       `db:"bank_name" json:"bank_name"`
	AccountNumber string       `db:"account_number" json:"account_number"`
	Deleted       sql.NullBool `db:"deleted" json:"deleted"`
	CreatedAt     time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt     sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullTime `db:"deleted_at" json:"deleted_at"`
	// use for handle hybrid concurrncy
	Rv sql.NullInt32 `db:"rv" json:"rv"`
}

type Cred struct {
	ID         int32        `db:"id" json:"id"`
	HashedPass string       `db:"hashed_pass" json:"hashed_pass"`
	Deleted    sql.NullBool `db:"deleted" json:"deleted"`
	CreatedAt  time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt  sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt  sql.NullTime `db:"deleted_at" json:"deleted_at"`
}

type Role struct {
	ID        int32        `db:"id" json:"id"`
	RoleName  string       `db:"role_name" json:"role_name"`
	Deleted   sql.NullBool `db:"deleted" json:"deleted"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
	// use for handle hybrid concurrncy
	Rv sql.NullInt32 `db:"rv" json:"rv"`
}

type Team struct {
	ID        int32         `db:"id" json:"id"`
	TeamName  string        `db:"team_name" json:"team_name"`
	CeoID     sql.NullInt64 `db:"ceo_id" json:"ceo_id"`
	Manager   sql.NullInt64 `db:"manager" json:"manager"`
	Hr        sql.NullInt64 `db:"hr" json:"hr"`
	TechGuy   sql.NullInt64 `db:"tech_guy" json:"tech_guy"`
	Indsutry  string        `db:"indsutry" json:"indsutry"`
	Deleted   sql.NullBool  `db:"deleted" json:"deleted"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime  `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime  `db:"deleted_at" json:"deleted_at"`
	// use for handle hybrid concurrncy
	Rv sql.NullInt32 `db:"rv" json:"rv"`
}

type User struct {
	ID       int32  `db:"id" json:"id"`
	Email    string `db:"email" json:"email"`
	Username string `db:"username" json:"username"`
	// one to one
	UserInfoID sql.NullInt64 `db:"user_info_id" json:"user_info_id"`
	// one to one, cred contain deleted ones
	CredID sql.NullInt64 `db:"cred_id" json:"cred_id"`
	// many to one, role is parent
	RoleID sql.NullInt64 `db:"role_id" json:"role_id"`
	// many to one, team is parent
	TeamID sql.NullInt64 `db:"team_id" json:"team_id"`
	// one to many, user is parent
	AccountID sql.NullInt64 `db:"account_id" json:"account_id"`
	Deleted   sql.NullBool  `db:"deleted" json:"deleted"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime  `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime  `db:"deleted_at" json:"deleted_at"`
	// use for handle hybrid concurrncy
	Rv sql.NullInt32 `db:"rv" json:"rv"`
}

type UsersInfo struct {
	ID                 int32          `db:"id" json:"id"`
	FirstName          sql.NullString `db:"first_name" json:"first_name"`
	LastName           sql.NullString `db:"last_name" json:"last_name"`
	Dob                time.Time      `db:"dob" json:"dob"`
	CellPhone          sql.NullString `db:"cell_phone" json:"cell_phone"`
	HomePhone          sql.NullString `db:"home_phone" json:"home_phone"`
	WorkPhone          sql.NullString `db:"work_phone" json:"work_phone"`
	Avatar             sql.NullString `db:"avatar" json:"avatar"`
	WorkAddress        sql.NullString `db:"work_address" json:"work_address"`
	HomeAddress        sql.NullString `db:"home_address" json:"home_address"`
	CurrentCity        sql.NullString `db:"current_city" json:"current_city"`
	CurrentCountry     sql.NullString `db:"current_country" json:"current_country"`
	ZipCode            sql.NullString `db:"zip_code" json:"zip_code"`
	NationalNumber     sql.NullString `db:"national_number" json:"national_number"`
	NationalCardPic    sql.NullString `db:"national_card_pic" json:"national_card_pic"`
	PassportNumberType sql.NullString `db:"passport_number_type" json:"passport_number_type"`
	PassportPic        sql.NullString `db:"passport_pic" json:"passport_pic"`
	Deleted            sql.NullBool   `db:"deleted" json:"deleted"`
	CreatedAt          time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt          sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt          sql.NullTime   `db:"deleted_at" json:"deleted_at"`
	// use for handle hybrid concurrncy
	Rv sql.NullInt32 `db:"rv" json:"rv"`
}
