// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateCred(ctx context.Context, hashedPass string) (Cred, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateTeamBasic(ctx context.Context, arg CreateTeamBasicParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserBaseInfo(ctx context.Context, arg CreateUserBaseInfoParams) (UsersInfo, error)
}

var _ Querier = (*Queries)(nil)
