// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (UsersLogin, error)
	CreateUserInfo(ctx context.Context, arg CreateUserInfoParams) (UsersInfo, error)
}

var _ Querier = (*Queries)(nil)
