DROP TABLE IF EXISTS "users_info" CASCADE;

DROP TABLE IF EXISTS "users" CASCADE;

DROP TABLE IF EXISTS "creds" CASCADE;

DROP TABLE IF EXISTS "roles" CASCADE;

DROP TABLE IF EXISTS "teams" CASCADE;

DROP TABLE IF EXISTS "accounts" CASCADE;

DROP TABLE IF EXISTS "apps" CASCADE;

DROP TABLE IF EXISTS "accounts_users" CASCADE